datasources:
  default:
    url: 'jdbc:h2:file:./h2db/db/space;DB_CLOSE_DELAY=-1'
    username: 'space'
    password: ''
    driverClassName: 'org.h2.Driver'
    poolName: Hikari
    autoCommit: false