micronaut:
  application:
    name: Traktor
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

#datasources:
#  default:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/space`}
#    username: 'space'
#    password: ''
#    driverClassName: 'org.postgresql.Driver'
#    autoCommit: false
#    hikari:
#      poolName: Hikari
#      maximum-pool-size: 10
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true

flyway:
  datasources:
    default:
      enabled: true

netty:
  default:
    allocator:
      max-order: 3


